### ISSUE TITLE
Non-comma separator not working in labeled data sets

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-serial-plotter-webapp#15]
### Describe the problem

The official [Arduino Serial Plotter protocol specification](https://github.com/arduino/Arduino/blob/master/build/shared/ArduinoSerialPlotterProtocol.md#serialplotter-protocol) documents three supported data point separator characters:

- space
- tab
- comma

🐛 Separators other than commas are not working in data sets that are labeled

#### Equipment

- Arduino board
  You can also send the equivalent data directly to the web app if that is more convenient to you.

#### Steps

1. Upload the following sketch to your Arduino board:
   ```cpp
   void setup() {
     Serial.begin(9600);
   }
   void loop() {
     for (byte value = 0; value < 4; value++) {
       for (byte variableOffset = 0; variableOffset < 3; variableOffset++) {
         Serial.print("label");
         Serial.print(variableOffset);
         Serial.print(':');
         Serial.print(value + variableOffset);
         Serial.print("\t");
       }
       Serial.println();
     }
     delay(100);
   }
   ```
1. Open "**Serial Plotter**"
1. Select "**9600 baud**" from the dropdown baud rate menu at the bottom right corner of the "**Serial Plotter**" window.

🐛 Only a single variable is plotted:

![image](https://user-images.githubusercontent.com/8572152/188385941-ba5fc995-93b9-4f7f-a400-d7a3338b0297.png)

### Expected behavior

![serial-plotter-labeled](https://user-images.githubusercontent.com/8572152/188384460-1105633f-ccaa-4045-a2bc-bb6c2cdab350.png)

- Full support for all data point separators documented in the specification.
- Supported separators are consistent regardless of whether or not data points are labeled.

**OR**

- Clear documentation of breaking change
- Comprehensive survey and repair of all important content broken by change

### Version

https://github.com/arduino/arduino-serial-plotter-webapp/commit/eac6d39f3f5156390bc4f9e09cafcccc121248c9

### Operating system

Windows

### Operating system version

10

### Additional context

The demo works as expected when using the Arduino IDE 1.8.19 Serial Plotter.

---

Examples of existing programs broken by this bug:

- https://docs.arduino.cc/tutorials/nano-rp2040-connect/rp2040-microphone-basics / https://github.com/arduino/ArduinoCore-mbed/blob/master/libraries/PDM/examples/PDMSerialPlotter/PDMSerialPlotter.ino
- https://github.com/arduino/Arduino/blob/master/build/shared/ArduinoSerialPlotterProtocol.md#two-traces-with-label-send-every-time
- https://github.com/marhar/ArrbotMonitor

**Comment by nmzaheer** [comment]
I think conforming to the protocol would be a better option. I think the second proposal would involve a lot more effort and unnecessary since it is also a part of legacy Arduino.

I'd like to take a stab at it

**Comment by nmzaheer** [comment]
Looks like the relevant code is here https://github.com/arduino/Arduino/blob/69e91cab5cc6e0ee9280a1b8a3399d1b634a9eef/app/src/processing/app/SerialPlotter.java#L408

A regex expression is being used to include Space, Tab and Comma as delimiter values. I will try to replicate the same in React
