### ISSUE TITLE
Do a display range adjustable X-axis, Add repeatable options when displaying the same contents

### ISSUE THREAD

**Issue by breaker123** [arduino/arduino-serial-plotter-webapp#29]
When I use the Serial Plotter, I want to extend the display range of the horizontal axis time so that the latest data acquisition and the previous data acquisition can be displayed on the same graph.

Second, when the x-coordinate data is a cyclic change in a range, I want the x-coordinate data to be displayed within the range instead of forward.

**Comment by per1234** [comment]
> Do a display range adjustable X-axis

This request is now tracked in dedicated issues:

- https://github.com/arduino/arduino-ide/issues/803
- https://github.com/arduino/arduino-serial-plotter-webapp/issues/25

>Add repeatable options when displaying the same contents

This request is now tracked in the dedicated issue: https://github.com/arduino/arduino-ide/issues/1697
