### ISSUE TITLE
Add support for LF line breaks on records

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-serial-plotter-webapp#8]
## Describe the current behavior

The Arduino IDE Serial Plotter accepts data in a delimiter-separated format. Each record is terminated by a line break.

Currently, the only line break recognized by the Arduino IDE 2.x Serial Plotter is CRLF (`\r\n`).

The LF line ending is supported and officially specified as the line break character for the classic Arduino IDE Serial Plotter protocol:

https://github.com/arduino/Arduino/blob/master/build/shared/ArduinoSerialPlotterProtocol.md#serialplotter-protocol

> |                       |     |
> | --------------------- | --- |
> | End of message symbol | \n  |

## To reproduce

1. Upload the following sketch to an Arduino board
   ```cpp
   void setup() {
     Serial.begin(9600);
   }
   void loop() {
     Serial.print(random(10));
     Serial.print('\n');
   }
   ```
1. Open the Arduino IDE 2.x Serial Plotter.
1. Select "**9600 baud**" from the dropdown baud rate menu at the bottom right corner of the "**Serial Plotter**" window.
   :cry: the data are not plotted.
   ![image](https://user-images.githubusercontent.com/8572152/150196130-15c09a24-6e3f-4f52-93c4-6a5a3b2c83c7.png)
1. Close the Arduino IDE 2.x Serial Plotter.
1. Open the classic Arduino IDE Serial Plotter.
1. Select "**9600 baud**" from the dropdown baud rate menu at the bottom left corner of the "**Serial Plotter**" window.
   :slightly_smiling_face: the data are plotted.
   ![image](https://user-images.githubusercontent.com/8572152/150196057-7be7000c-8656-4070-9d63-9748e1f09048.png)

## Describe the request

Support LF in addition to CRLF line breaks in data sent to Serial Plotter.

## Desktop

- OS: Windows 10
- Arduino IDE Version: 2.0.0-rc3-snapshot.35e5da5
Date: 2022-01-13T17:15:54.562Z
CLI Version: 0.20.2 [13783819]

## Additional context

In addition to providing compatibility with the original protocol, there are several other reasons for supporting LF line breaks:

- "New Line" is the default line ending setting in the Arduino IDE Serial Monitor and Serial Plotter.
- A single character line break is more efficient, which can be an important consideration for resource constrained microcontrollers.
- Users may find LF line endings most intuitive since this is the standard line ending on both Linux and macOS, and even increasingly prevalent in code applications on Windows.

**Comment by nmzaheer** [comment]
I think the separator in the classic Serial Plotter code is given as
`      int linebreak = messageBuffer.indexOf("\n");` [Link](https://github.com/arduino/Arduino/blob/71f9d67a5118fc1b52360961c4186b1e50f6d54e/app/src/processing/app/SerialPlotter.java#L196)

 whereas in the Serial Plotter webapp is given as
`const separator = "\r\n";` [Link](https://github.com/arduino/arduino-serial-plotter-webapp/blob/04a460e0c21609a63c4064f561990c0128c5a0ed/src/msgAggregatorWorker.ts#L21) 

This makes it clear that the webapp is handling it differently from the classic Serial Plotter.

Can a PR be submitted changing this? or am I missing something?

**Comment by per1234** [comment]
Hi @nmzaheer. Yes, please do submit a pull request. I'll be happy to review and merge it.
